apiVersion: v1
kind: Pod
metadata:
  name: cloud-pod
  labels:
    app: cloud
spec:
  hostNetwork: true
  containers:
  - name: api-container
    image: sakred22/k3s-demo:cloud
    imagePullPolicy: Always  
    ports:
    - containerPort: 5000  
    - containerPort: 8000  
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-service
spec:
  selector:
    app: cloud
  ports:
    - name: api-port   
      protocol: TCP
      port: 5000       
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  name: edge1-pod
  labels:
    app: edge1
spec:
  containers:
  - name: edge1-container
    image: sakred22/k3s-demo:edge1
    imagePullPolicy: Always  # Always pull the latest image

---
apiVersion: v1
kind: Service
metadata:
  name: edge1-service
spec:
  selector:
    app: edge1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: edge2-pod
  labels:
    app: edge2
spec:
  containers:
  - name: edge2-container
    image: sakred22/k3s-demo:edge2
    imagePullPolicy: Always  # Always pull the latest image
    command: ["/bin/sh", "-c"]
    args: ["while true; do sleep 3600; done"]

---

apiVersion: v1
kind: Service
metadata:
  name: edge2-service
spec:
  selector:
    app: edge2
  ports:
    - name: http-port  
      protocol: TCP
      port: 80        
      targetPort: 80  

