apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
      - name: cloud-container
        image: sakred22/k3s-demo:cloud
        imagePullPolicy: Always  # Always pull the latest image
        ports:
        - containerPort: 5000  # API port
        - containerPort: 80     # UI port
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-service
spec:
  selector:
    app: cloud
  ports:
    - name: ui-port   # Name for UI port
      protocol: TCP
      port: 80        # Expose UI port
      targetPort: 80
    - name: api-port  # Name for API port
      protocol: TCP
      port: 5000      # Expose API port
      targetPort: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge1
  template:
    metadata:
      labels:
        app: edge1
    spec:
      containers:
      - name: edge1-container
        image: sakred22/k3s-demo:edge1
        imagePullPolicy: Always  # Always pull the latest image
---
apiVersion: v1
kind: Pod
metadata:
  name: edge2-pod
  labels:
    app: edge2
spec:
  containers:
  - name: edge2-container
    image: sakred22/k3s-demo:edge2
    command: ["/bin/sh", "-c"]
    args: ["while true; do sleep 3600; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: edge2-service
spec:
  selector:
    app: edge2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: edge1-pod
  labels:
    app: edge1
spec:
  containers:
  - name: edge1-container
    image: sakred22/k3s-demo:edge1
    command: ["/bin/sh", "-c"]
    args: ["/sendText.sh"]
