apiVersion: v1
kind: Pod
metadata:
  name: cloud-pod
  labels:
    app: cloud
spec:
  nodeName: cloud
  hostNetwork: true
  containers:
  - name: api-container
    image: sakred22/k3s-demo:cloud
    imagePullPolicy: Always  
    ports:
    - containerPort: 5000  
    - containerPort: 8000  
---
apiVersion: v1
kind: Pod
metadata:
  name: edge1-pod
  labels:
    app: edge1
spec:
  nodeName: edge1
  containers:
  - name: edge1-container
    image: sakred22/k3s-demo:edge1
    imagePullPolicy: Always  # Always pull the latest image
---
apiVersion: v1
kind: Pod
metadata:
  name: edge2-pod
  labels:
    app: edge2
spec:
  nodeName: edge2
  containers:
  - name: edge2-container
    image: sakred22/k3s-demo:edge2
    imagePullPolicy: Always  # Always pull the latest image
    command: ["/bin/sh", "-c"]
    args: ["while true; do sleep 3600; done"]
