apiVersion: v1
kind: Service
metadata:
  name: edge2-service
spec:
  selector:
    app: edge2
  ports:
    - name: http-port  
      protocol: TCP
      port: 80        
      targetPort: 80  

---

apiVersion: v1
kind: Service
metadata:
  name: edge1-service
spec:
  selector:
    app: edge1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-service
spec:
  selector:
    app: cloud
  ports:
    - name: api-port   
      protocol: TCP
      port: 5000       
  type: ClusterIP
